### ISSUE TITLE
The type 'Dynamic' is missing, is there any replacement?

### ISSUE THREAD

**Issue by Flex-Xuan** [neuroglia-io/framework#71]
**Describe the bug**
It seems that the type '[Dynamic](https://github.com/neuroglia-io/framework/blob/v2.1.4/src/Serialization/Neuroglia.Serialization.Dynamic/Dynamic.cs)' was removed in the new version. 

Is there any reason, or is there any replacement? 

It is quite useful when serialize the dynamic data to database.

**Comment by cdavernas** [comment]
Yes, the `Dynamic` type has been dropped starting from 3.0.0 because it created a consequent overhead when writing models, and especially when reading them. It severely impacted performance when using large objects and/or arrays.
We now instead prefer declaring objects, and implicitly using JsonElements/JsonNodes, thus relying on the native and extremely performant System.Text.Json serializer.
If need arises, I could however easily add a new Dynamics package with a couple of adjustments.

Does that answer your question?
